# pull all portfolio project images from docker hub

services:

  apache:
    container_name: apache-server
    environment:
      ENV: ${ENV}
    image: httpd:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '80:80'
    volumes:
    - ./homepage:/usr/local/apache2/htdocs
    - ./.conf-${ENV}:/usr/local/apache2/conf/httpd.conf:ro

  # react-course-admin
  react-course-admin_web:
    container_name: react-course-admin_web
    environment:
      ENV: ${ENV}
    image: incerto13/react-course-admin_web:${ENV}-latest
    ports:
      - 8011:80
  react-course-admin_server:
    container_name: react-course-admin_server
    environment:
      ENV: ${ENV}
    image: incerto13/react-course-admin_server:${ENV}-latest
    ports:
      - 8111:3001

  react-electoral-map:
    container_name: react-electoral-map
    environment:
      ENV: ${ENV}
    image: incerto13/react-electoral-map:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8012:80
    
  # react-to-do
  react-to-do_web:
    container_name: react-to-do_web
    environment:
      ENV: ${ENV}
    image: incerto13/react-to-do_web:${ENV}-latest
    ports:
      - 8010:80
  react-to-do_server:
    container_name: react-to-do_server
    environment:
      ENV: ${ENV}
    image: incerto13/react-to-do_server:${ENV}-latest
    ports:
      - 8110:3001