# these containers are only used for attaining and periodically renewing ssl certs

services: 

  nginx:
    container_name: nginx
    environment:
      ENV: ${ENV}
    image: nginx:latest
    restart: unless-stopped
    ports:
    - 80:80
    volumes:
      - ./nginx/default.conf-ssl-challenge-${ENV}:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot-init:
    container_name: certbot-init
    image: certbot/certbot
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      BASE_DOMAIN: ${BASE_DOMAIN} 
      REACT_TO_DO_DOMAIN: ${REACT_TO_DO_DOMAIN}
      REACT_ELECTORAL_MAP_DOMAIN: ${REACT_ELECTORAL_MAP_DOMAIN}
      REACT_COURSE_ADMIN_DOMAIN: ${REACT_COURSE_ADMIN_DOMAIN}
      NEST_TO_DO_API_DOMAIN: ${NEST_TO_DO_API_DOMAIN}
      NEST_BLOG_API_DOMAIN: ${NEST_BLOG_API_DOMAIN}
      NEST_COURSE_ADMIN_API_DOMAIN: ${NEST_COURSE_ADMIN_API_DOMAIN}
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ["sleep", "infinity"]

    # command: >
    #       bash -c "certbot certonly \
    #         --webroot -w /var/www/certbot \
    #         --force-renewal \
    #         --email ${LETSENCRYPT_EMAIL} \
    #         -d ${BASE_DOMAIN} \
    #         -d ${REACT_TO_DO_DOMAIN} \
    #         -d ${REACT_ELECTORAL_MAP_DOMAIN} \
    #         -d ${REACT_COURSE_ADMIN_DOMAIN} \
    #         -d ${NEST_TO_DO_API_DOMAIN} \
    #         -d ${NEST_BLOG_API_DOMAIN} \
    #         -d ${NEST_COURSE_ADMIN_API_DOMAIN} \
    #         --agree-tos"

  certbot-renew:
    container_name: certbot-renew
    image: certbot/certbot
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      BASE_DOMAIN: ${BASE_DOMAIN} 
      REACT_COURSE_ADMIN_DOMAIN: ${REACT_COURSE_ADMIN_DOMAIN}
      REACT_ELECTORAL_MAP_DOMAIN: ${REACT_ELECTORAL_MAP_DOMAIN}
      REACT_TO_DO_DOMAIN: ${REACT_TO_DO_DOMAIN}
      NEST_TO_DO_API_DOMAIN: ${NEST_TO_DO_API_DOMAIN}
      NEST_BLOG_API_DOMAIN: ${NEST_BLOG_API_DOMAIN}
      NEST_COURSE_ADMIN_API_DOMAIN: ${NEST_COURSE_ADMIN_API_DOMAIN}
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
          sh -c "--webroot -w /var/www/certbot \
            --force-renewal \
            --email ${LETSENCRYPT_EMAIL} \
            -d ${BASE_DOMAIN} \
            -d ${REACT_TO_DO_DOMAIN} \
            -d ${REACT_ELECTORAL_MAP_DOMAIN} \
            -d ${REACT_COURSE_ADMIN_DOMAIN} \
            -d ${NEST_TO_DO_API_DOMAIN} \
            -d ${NEST_BLOG_API_DOMAIN} \
            -d ${NEST_COURSE_ADMIN_API_DOMAIN} \
            --agree-tos"

