# these containers are only used for attaining and periodically renewing ssl certs

services: 

  nginx:
    container_name: nginx
    environment:
      ENV: ${ENV}
    image: nginx:latest
    restart: unless-stopped
    ports:
    - 80:80
    volumes:
      - ./.conf-init-ssl-challenge:/etc/nginx/conf.d/default.conf

  certbot-init:
    container_name: certbot
    image: certbot/certbot
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      DOMAINS: ${DOMAINS}
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email "$LETSENCRYPT_EMAIL" -d "$DOMAINS" --agree-tos

  certbot-renew:
    container_name: certbot-renew
    image: certbot/certbot
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      DOMAINS: ${DOMAINS}
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --renew --email "$LETSENCRYPT_EMAIL" -d "$DOMAINS" --agree-tos

