# pull all portfolio project images from docker hub

services:

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./.conf-${ENV}:/etc/nginx/conf.d/default.conf
      - ./staging/conf:/etc/letsencrypt  # change volume dir as needed but never path within container
      - ./staging/www:/var/www/certbot  # change volume dir as needed but never path within container
    
  homepage:
    container_name: homepage
    image: incerto13/homepage:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8080:80

  # react-course-admin
  react-course-admin_web:
    container_name: react-course-admin_web
    image: incerto13/react-course-admin_web:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8011:80
  react-course-admin_server:
    container_name: react-course-admin_server
    image: incerto13/react-course-admin_server:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8111:3001

  react-electoral-map:
    container_name: react-electoral-map
    image: incerto13/react-electoral-map:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8012:80
    
  # react-to-do
  react-to-do_postgres:
    container_name: react-to-do_postgres
    image: incerto13/react-to-do_postgres:${ENV}-latest
    environment:      
      POSTGRES_DB: react-to-do     
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: postgres
    ports:
      - "${REACT_TO_DO_POSTGRES_PORT}:5432"
    restart: unless-stopped
  react-to-do_web:
    container_name: react-to-do_web
    image: incerto13/react-to-do_web:${ENV}-latest
    ports:
      - "${REACT_TO_DO_WEB_PORT}:80"
    restart: unless-stopped
  react-to-do_server:
    container_name: react-to-do_server
    image: incerto13/react-to-do_server:${ENV}-latest
    environment:
      REACT_TO_DO_TYPEORM_HOST: $REACT_TO_DO_TYPEORM_HOST
      REACT_TO_DO_POSTGRES_PORT: $REACT_TO_DO_POSTGRES_PORT
    ports:
      - "${REACT_TO_DO_SERVER_PORT}:3001"
    restart: unless-stopped