# build all projects locally, should only have server and hompeage here

services:

  apache-server:
    image: httpd:latest
    container_name: apache-server
    ports:
    - 80:80
    volumes:
    - ./homepage:/usr/local/apache2/htdocs
    - ./.conf-dev:/usr/local/apache2/conf/httpd.conf:ro

      


