# pull all portfolio project images from docker hub

services:

  nginx-proxy:
    container_name: nginx-proxy
    environment:
      ENV: ${ENV}
    image: nginx:latest
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./.conf-${ENV}:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes: 
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  homepage:
    container_name: homepage
    environment:
      ENV: ${ENV}
    image: incerto13/homepage:${ENV}-latest
    restart: unless-stopped
    ports:
    - 8080:80

  # react-course-admin
  react-course-admin_web:
    container_name: react-course-admin_web
    environment:
      ENV: ${ENV}
    image: incerto13/react-course-admin_web:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8011:80
  react-course-admin_server:
    container_name: react-course-admin_server
    environment:
      ENV: ${ENV}
    image: incerto13/react-course-admin_server:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8111:3001

  react-electoral-map:
    container_name: react-electoral-map
    environment:
      ENV: ${ENV}
    image: incerto13/react-electoral-map:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8012:80
    
  # react-to-do
  react-to-do_web:
    container_name: react-to-do_web
    environment:
      ENV: ${ENV}
    image: incerto13/react-to-do_web:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8010:80
  react-to-do_server:
    container_name: react-to-do_server
    environment:
      ENV: ${ENV}
    image: incerto13/react-to-do_server:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8110:3001