name: Run Certbot Revoke in Prod Env

# configure manual trigger only 
on: workflow_dispatch

env: 
  ENV: prod
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ENVS: ${{ secrets.PROD_ENVS }}

jobs:
  certbot-revoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOSTNAME  }}
          username: ${{ secrets.EC2_USERNAME  }}
          key: ${{ secrets.PROD_AWS_PRIVATE_KEY  }}
          port: 22
          envs: ENVS
          script: |
            docker kill $(docker ps -q)
            docker system prune -a -f
            cd incertotech-k8
            echo "$ENVS" | sudo tee .env > /dev/null
            git checkout main
            git pull origin main
            sudo docker compose -f docker-compose.ssl.yml pull
            bash run-certbot-revoke.sh 
            echo sleep 60 seconds...
            sleep 60
            docker kill $(docker ps -q)
            docker system prune -a -f