name: Deploy to Prod Env

# configure manual trigger only 
on: workflow_dispatch

env: 
  ENV: prod
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ENVS: ${{ secrets.PROD_ENVS }}
  NGINX_DEFAULT_CONF: ${{ secrets.PROD_NGINX_DEFAULT_CONF }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOSTNAME  }}
          username: ${{ secrets.EC2_USERNAME  }}
          key: ${{ secrets.PROD_AWS_PRIVATE_KEY  }}
          port: 22
          envs: ENV, ENVS, NGINX_DEFAULT_CONF
          script: |
            cd incertotech-k8
            echo "$ENVS" | sudo tee .env > /dev/null
            mkdir -p nginx 
            echo "$NGINX_DEFAULT_CONF" > "nginx/default.conf-${ENV}"
            git pull origin $ENV
            docker system prune -a -f
            sudo docker compose pull
            bash run-docker.sh 

