name: Deploy to Staging Env

# configure manual trigger only 
on: workflow_dispatch

env: 
  ENV: staging
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ENVS: ${{ secrets.STAGING_ENVS }}
  APACHE_CONF: ${{ secrets.STAGING_APACHE_CONF }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_EC2_HOSTNAME  }}
          username: ${{ secrets.EC2_USERNAME  }}
          key: ${{ secrets.STAGING_AWS_PRIVATE_KEY  }}
          port: 22
          envs: ENV, ENVS, APACHE_CONF
          script: |
            cd incertotech-k8
            echo "$ENVS" > .env
            echo "$APACHE_CONF" > ".conf-${ENV}"
            git pull origin $ENV
            docker system prune -a -f
            sudo docker compose pull
            bash run-docker.sh 

