name: Run Certbot Init in Staging Env

# configure manual trigger only 
on: workflow_dispatch

env: 
  ENV: staging
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ENVS: ${{ secrets.STAGING_ENVS }}
  NGINX_INIT_SSL_CONF: ${{ secrets.NGINX_INIT_SSL_CONF }}

jobs:
  certbot-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_EC2_HOSTNAME  }}
          username: ${{ secrets.EC2_USERNAME  }}
          key: ${{ secrets.STAGING_AWS_PRIVATE_KEY  }}
          port: 22
          envs: ENV, ENVS, NGINX_INIT_SSL_CONF
          script: |
            docker kill $(docker ps -q)
            docker system prune -a -f
            cd incertotech-k8
            sudo rm -rf certbot
            echo "$ENVS" | sudo tee .env > /dev/null
            mkdir -p nginx 
            echo "$NGINX_INIT_SSL_CONF" > nginx/default.conf-init-ssl-challenge
            git pull origin $ENV
            docker system prune -a -f
            sudo docker compose pull
            bash run-certbot-init.sh 
            sleep 60
            docker kill $(docker ps -q)

